
production:
  adapter: postgresql
  username: brgen
  # password: #{ Settings.database.password }
  password: IeY3ieta
  database: brgen

# -------------------------------------------------

development:
  adapter: postgresql

  # Will log in as system user if `username` is commented

  # username: brgen
  # password: #{ Settings.database.password }
  password: IeY3ieta
  database: brgen_dev

# -------------------------------------------------

test:
  adapter: postgresql
  username: brgen
  # password: #{ Settings.database.password }
  password: IeY3ieta
  database: brgen_test

