source "https://rubygems.org" do
  gem "rails", "4.2.5"
  gem "rails-i18n"
  gem "json"
  gem "i18n-js", github: "fnando/i18n-js"

  # Application server

  gem "puma"

  # -------------------------------------------------

  # Required for Nokogiri to build

  gem "pkg-config"

  # -------------------------------------------------

  # CORE

  # Forum engine

  gem "forem", github: "rubysherpas/forem", branch: "rails4"

  # Nested set pattern for ActiveRecord models

  gem "awesome_nested_set", github: "collectiveidea/awesome_nested_set"

  # OpenBSD `bcrypt()` password hashing algorithm

  gem "bcrypt"

  # ActiveRecord integration for Delayed::Job

  gem "delayed_job_active_record"

  # HTTP User Agent parser

  gem "useragent"

  # Cron jobs

  gem "whenever"

  # Event-driven I/O and lightweight concurrency library

  gem "eventmachine", github: "eventmachine/eventmachine"

  # -------------------------------------------------

  # SECURITY

  # Rack middleware for blocking and throttling

  gem "rack-attack"

  # -------------------------------------------------

  # DATABASE

  # PostgreSQL RDBMS

  gem "pg"

  # ActiveRecord named scopes that take advantage of PostgreSQL's full text search

  gem "pg_search"

  # Annotate ActiveRecord models

  gem "annotate"

  # -------------------------------------------------

  # USERS

  # Flexible authentication solution for Rails with Warden

  gem "devise"
  gem "devise-i18n"

  # User resource restrictions

  gem "cancancan"

  # Facebook OAuth2 Strategy for OmniAuth

  gem "omniauth-facebook"

  # OAuth authentication, the Graph and REST APIs, realtime updates, and test users

  gem "koala"

  # Google OAuth2 strategy for OmniAuth

  gem "omniauth-google-oauth2"

  # Instagram OAuth2 strategy for OmniAuth

  gem "omniauth-instagram"

  # -------------------------------------------------

  # FORMS

  # DSL with no opinion on markup

  gem "simple_form", github: "plataformatec/simple_form"

  # -------------------------------------------------

  # MEDIA

  # File attachment management for ActiveRecord

  gem "paperclip", "4.3.7"

  # Image compression

  gem "image_optim"
  gem "paperclip-optimizer"

  # FFmpeg video conversion

  gem "paperclip-av-transcoder"
  gem "paperclip-av-qtfaststart", github: "ruby-av/paperclip-av-qtfaststart"

  # Process Paperclip attachments with Delayed::Job

  gem "delayed_paperclip", "2.10.0"
  gem "daemons"

  # ImageMagick image processing library

  gem "rmagick", github: "rmagick/rmagick"

  # -------------------------------------------------

  # POSTS

  # Fast, pure Ruby Markdown superset converter

  gem "kramdown"

  # Emoji images and names

  gem "gemoji"

  # Autolinking

  gem "rinku"

  # Text processing routines for Twitter Tweets

  gem "twitter-text"

  # Clean, powerful, customizable and sophisticated paginator

  gem "kaminari"

  # Identicons

  gem "quilt"

  # -------------------------------------------------

  # ASSETS

  group :production do

    # Run JavaScript code from Ruby

    gem "execjs"

    # Wrapper for UglifyJS JavaScript compressor

    gem "uglifier"

    # Stylesheet engine and CSS compressor

    gem "sass-rails"
  end

  # -------------------------------------------------

  # DEVELOPMENT

  group :development do

    # Live browser reloads for views, CSS and JS

    # gem "guard"
    # gem "guard-livereload"

    # Debugging in Ruby 2

    # gem "byebug"

    # Application preloader for faster tests, migrations and tasks

    # http://github.com/rails/spring#deployment

    # gem "spring"
  end

  # Speed measuring tool originally built at GitHub

  # gem "peek"
  # gem "peek-rblineprof"
  # gem "peek-pg"
  # gem "peek-delayedjob"
  # gem "peek-redis"
  # gem "peek-sidekiq"

  # -------------------------------------------------

  # SEO

  # Generate and submit XML sitemaps to Google

  gem "sitemap_generator"

  # -------------------------------------------------

  # AFFILIATE PRODUCTS

  # Simple HTTP and REST client

  gem "rest-client"

  # Classes and mixins to make hashes more powerful

  gem "hashie"

  # -------------------------------------------------

  # REALTIME STREAMING

  gem "sidekiq"
  gem "redis"

  # Twitter

  gem "tweetstream"

  # -------------------------------------------------

  group :development, :test do
    gem "rspec-rails"
    gem "factory_girl_rails", "~> 4.0"
    gem "pry"
  end

  group :test do
    gem "webmock"
    gem "rspec-sidekiq"
  end

  # -------------------------------------------------

  # TODO: Remove once `rails-assets-jquery-oembed-all` becomes available

  gem "jquery-oembed-rails"
end

# -------------------------------------------------

# BOWER PROXY

source "https://rails-assets.org" do

  # CORE

  # TODO: jQuery 2.2.0 breaks jQuery Mobile 1.4.5

  gem "rails-assets-jquery", "2.1.4"
  gem "rails-assets-jquery-ujs"

  # CSS3 vendor prefix generator

  gem "rails-assets-cssfx"

  # Awesome Media Queries in JavaScript

  gem "rails-assets-enquire"

  # Slim progress bars

  gem "rails-assets-nprogress"

  # -------------------------------------------------

  # POSTS

  # Embeddable media from over 300 content providers

  gem "rails-assets-embedly-jquery"

  # Use native oEmbed for Instagram and Twitter streaming

  # gem "rails-assets-jquery-oembed-all"

  # Know when images are done loading

  gem "rails-assets-imagesloaded"

  # Bin-packing layout library

  gem "rails-assets-packery", "2.1.0"
  gem "rails-assets-jquery-bridget"

  # Check if an element is within the browsers visual viewport

  gem "rails-assets-jquery.visible"

  # Pretty URL creation

  gem "rails-assets-jquery-slugify"
  gem "rails-assets-speakingurl"

  # Autolinking

  gem "rails-assets-Autolinker.js"

  # -------------------------------------------------

  # FORMS

  # Twitter autocomplete library

  gem "rails-assets-core-typeahead"

  # Fading labels

  gem "rails-assets-jquery-infield-label"

  # Text / select box hybrid

  gem "rails-assets-selectize", "0.12.1"
  gem "rails-assets-sifter"
  gem "rails-assets-microplugin"

  # -------------------------------------------------

  # DESKTOP

    # CORE

    # Attempt to determine the user"s intent when moving the mouse

    gem "rails-assets-jquery-hoverIntent"

    # Truncation

    gem "rails-assets-jquery.ellipsis"

    # -------------------------------------------------

    # AFFILIATE PRODUCTS

    # Parallax engine that reacts to the orientation of smart devices

    gem "rails-assets-parallax"

    # -------------------------------------------------

    # PHOTO EDITOR

    # Centers DOM elements

    gem "rails-assets-jquery.center.js"

  # -------------------------------------------------

  # MOBILE

    # CORE

    # High performance JavaScript scroller

    gem "rails-assets-iscroll", "5.1.2"

    # Add to home screen call-out for mobile devices

    gem "rails-assets-add-to-homescreen"

    # Facebook-style side menu

    gem "rails-assets-snapjs"

    # -------------------------------------------------

    # PHOTO EDITOR

    # Simple, scaleable carousels

    gem "rails-assets-jquery.caro"

  # -------------------------------------------------

  # PHOTO EDITOR

  # JavaScript HTML5 canvas manipulation

  gem "rails-assets-caman"

  # Seeded random number generator

  gem "rails-assets-seedrandom"

  # Decodes and populates serialized form data

  gem "rails-assets-jquery-deserialize"
end

